/*
 * This file is generated by jOOQ.
 */
package com.tdj.jooq;


import com.tdj.jooq.tables.CwSum;
import com.tdj.jooq.tables.records.CwSumRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in 
 * test.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<CwSumRecord> KEY_CW_SUM_PRIMARY = Internal.createUniqueKey(CwSum.CW_SUM, DSL.name("KEY_cw_sum_PRIMARY"), new TableField[] { CwSum.CW_SUM.ID }, true);
}
