/*
 * This file is generated by jOOQ.
 */
package com.tdj.jooq;


import com.tdj.jooq.tables.CwSum;


/**
 * Convenience access to all tables in test.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * 车位统计
     */
    public static final CwSum CW_SUM = CwSum.CW_SUM;
}
