/*
 * This file is generated by jOOQ.
 */
package com.tdj.jooq.tables.pojos;


import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.tdj.jooq.tables.interfaces.ICwSum;

import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;

import java.math.BigDecimal;
import java.time.LocalDateTime;


import static io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo.*;
/**
 * 车位统计
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CwSum implements VertxPojo, ICwSum {

    private static final long serialVersionUID = 1L;

    private Long          id;
    @JsonProperty("receivable_amount")
    private BigDecimal    receivableAmount;
    @JsonProperty("discount_amount")
    private BigDecimal    discountAmount;
    @JsonProperty("parking_coupon_discount_amount")
    private BigDecimal    parkingCouponDiscountAmount;
    @JsonProperty("remission_amount")
    private BigDecimal    remissionAmount;
    @JsonProperty("actual_amount")
    private BigDecimal    actualAmount;
    @JsonProperty("cancel_amount")
    private BigDecimal    cancelAmount;
    @JsonProperty("park_name")
    private String        parkName;
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private LocalDateTime time;

    public CwSum() {}

    public CwSum(ICwSum value) {
        this.id = value.getId();
        this.receivableAmount = value.getReceivableAmount();
        this.discountAmount = value.getDiscountAmount();
        this.parkingCouponDiscountAmount = value.getParkingCouponDiscountAmount();
        this.remissionAmount = value.getRemissionAmount();
        this.actualAmount = value.getActualAmount();
        this.cancelAmount = value.getCancelAmount();
        this.parkName = value.getParkName();
        this.time = value.getTime();
    }

    public CwSum(
        Long          id,
        BigDecimal    receivableAmount,
        BigDecimal    discountAmount,
        BigDecimal    parkingCouponDiscountAmount,
        BigDecimal    remissionAmount,
        BigDecimal    actualAmount,
        BigDecimal    cancelAmount,
        String        parkName,
        LocalDateTime time
    ) {
        this.id = id;
        this.receivableAmount = receivableAmount;
        this.discountAmount = discountAmount;
        this.parkingCouponDiscountAmount = parkingCouponDiscountAmount;
        this.remissionAmount = remissionAmount;
        this.actualAmount = actualAmount;
        this.cancelAmount = cancelAmount;
        this.parkName = parkName;
        this.time = time;
    }

        public CwSum(io.vertx.core.json.JsonObject json) {
                this();
                fromJson(json);
        }

    /**
     * Getter for <code>test.cw_sum.id</code>.
     */
    @Override
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>test.cw_sum.id</code>.
     */
    @Override
    public CwSum setId(Long id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>test.cw_sum.receivable_amount</code>. 应收金额
     */
    @Override
    public BigDecimal getReceivableAmount() {
        return this.receivableAmount;
    }

    /**
     * Setter for <code>test.cw_sum.receivable_amount</code>. 应收金额
     */
    @Override
    public CwSum setReceivableAmount(BigDecimal receivableAmount) {
        this.receivableAmount = receivableAmount;
        return this;
    }

    /**
     * Getter for <code>test.cw_sum.discount_amount</code>. 抵扣金额
     */
    @Override
    public BigDecimal getDiscountAmount() {
        return this.discountAmount;
    }

    /**
     * Setter for <code>test.cw_sum.discount_amount</code>. 抵扣金额
     */
    @Override
    public CwSum setDiscountAmount(BigDecimal discountAmount) {
        this.discountAmount = discountAmount;
        return this;
    }

    /**
     * Getter for <code>test.cw_sum.parking_coupon_discount_amount</code>. 商家停车券抵扣金额
     */
    @Override
    public BigDecimal getParkingCouponDiscountAmount() {
        return this.parkingCouponDiscountAmount;
    }

    /**
     * Setter for <code>test.cw_sum.parking_coupon_discount_amount</code>. 商家停车券抵扣金额
     */
    @Override
    public CwSum setParkingCouponDiscountAmount(BigDecimal parkingCouponDiscountAmount) {
        this.parkingCouponDiscountAmount = parkingCouponDiscountAmount;
        return this;
    }

    /**
     * Getter for <code>test.cw_sum.remission_amount</code>. 车位减免金额(元)
     */
    @Override
    public BigDecimal getRemissionAmount() {
        return this.remissionAmount;
    }

    /**
     * Setter for <code>test.cw_sum.remission_amount</code>. 车位减免金额(元)
     */
    @Override
    public CwSum setRemissionAmount(BigDecimal remissionAmount) {
        this.remissionAmount = remissionAmount;
        return this;
    }

    /**
     * Getter for <code>test.cw_sum.actual_amount</code>. 实收金额
     */
    @Override
    public BigDecimal getActualAmount() {
        return this.actualAmount;
    }

    /**
     * Setter for <code>test.cw_sum.actual_amount</code>. 实收金额
     */
    @Override
    public CwSum setActualAmount(BigDecimal actualAmount) {
        this.actualAmount = actualAmount;
        return this;
    }

    /**
     * Getter for <code>test.cw_sum.cancel_amount</code>. 注销金额
     */
    @Override
    public BigDecimal getCancelAmount() {
        return this.cancelAmount;
    }

    /**
     * Setter for <code>test.cw_sum.cancel_amount</code>. 注销金额
     */
    @Override
    public CwSum setCancelAmount(BigDecimal cancelAmount) {
        this.cancelAmount = cancelAmount;
        return this;
    }

    /**
     * Getter for <code>test.cw_sum.park_name</code>. 车场名称
     */
    @Override
    public String getParkName() {
        return this.parkName;
    }

    /**
     * Setter for <code>test.cw_sum.park_name</code>. 车场名称
     */
    @Override
    public CwSum setParkName(String parkName) {
        this.parkName = parkName;
        return this;
    }

    /**
     * Getter for <code>test.cw_sum.time</code>.
     */
    @Override
    public LocalDateTime getTime() {
        return this.time;
    }

    /**
     * Setter for <code>test.cw_sum.time</code>.
     */
    @Override
    public CwSum setTime(LocalDateTime time) {
        this.time = time;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("CwSum (");

        sb.append(id);
        sb.append(", ").append(receivableAmount);
        sb.append(", ").append(discountAmount);
        sb.append(", ").append(parkingCouponDiscountAmount);
        sb.append(", ").append(remissionAmount);
        sb.append(", ").append(actualAmount);
        sb.append(", ").append(cancelAmount);
        sb.append(", ").append(parkName);
        sb.append(", ").append(time);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(ICwSum from) {
        setId(from.getId());
        setReceivableAmount(from.getReceivableAmount());
        setDiscountAmount(from.getDiscountAmount());
        setParkingCouponDiscountAmount(from.getParkingCouponDiscountAmount());
        setRemissionAmount(from.getRemissionAmount());
        setActualAmount(from.getActualAmount());
        setCancelAmount(from.getCancelAmount());
        setParkName(from.getParkName());
        setTime(from.getTime());
    }

    @Override
    public <E extends ICwSum> E into(E into) {
        into.from(this);
        return into;
    }
}
