/*
 * This file is generated by jOOQ.
 */
package com.tdj.jooq.tables.interfaces;


import com.tdj.jooq.tables.pojos.CwSum;
import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;

import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDateTime;


import static io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo.*;
/**
 * 车位统计
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface ICwSum extends VertxPojo, Serializable {

    /**
     * Setter for <code>test.cw_sum.id</code>.
     */
    public ICwSum setId(Long value);

    /**
     * Getter for <code>test.cw_sum.id</code>.
     */
    public Long getId();

    /**
     * Setter for <code>test.cw_sum.receivable_amount</code>. 应收金额
     */
    public ICwSum setReceivableAmount(BigDecimal value);

    /**
     * Getter for <code>test.cw_sum.receivable_amount</code>. 应收金额
     */
    public BigDecimal getReceivableAmount();

    /**
     * Setter for <code>test.cw_sum.discount_amount</code>. 抵扣金额
     */
    public ICwSum setDiscountAmount(BigDecimal value);

    /**
     * Getter for <code>test.cw_sum.discount_amount</code>. 抵扣金额
     */
    public BigDecimal getDiscountAmount();

    /**
     * Setter for <code>test.cw_sum.parking_coupon_discount_amount</code>. 商家停车券抵扣金额
     */
    public ICwSum setParkingCouponDiscountAmount(BigDecimal value);

    /**
     * Getter for <code>test.cw_sum.parking_coupon_discount_amount</code>. 商家停车券抵扣金额
     */
    public BigDecimal getParkingCouponDiscountAmount();

    /**
     * Setter for <code>test.cw_sum.remission_amount</code>. 车位减免金额(元)
     */
    public ICwSum setRemissionAmount(BigDecimal value);

    /**
     * Getter for <code>test.cw_sum.remission_amount</code>. 车位减免金额(元)
     */
    public BigDecimal getRemissionAmount();

    /**
     * Setter for <code>test.cw_sum.actual_amount</code>. 实收金额
     */
    public ICwSum setActualAmount(BigDecimal value);

    /**
     * Getter for <code>test.cw_sum.actual_amount</code>. 实收金额
     */
    public BigDecimal getActualAmount();

    /**
     * Setter for <code>test.cw_sum.cancel_amount</code>. 注销金额
     */
    public ICwSum setCancelAmount(BigDecimal value);

    /**
     * Getter for <code>test.cw_sum.cancel_amount</code>. 注销金额
     */
    public BigDecimal getCancelAmount();

    /**
     * Setter for <code>test.cw_sum.park_name</code>. 车场名称
     */
    public ICwSum setParkName(String value);

    /**
     * Getter for <code>test.cw_sum.park_name</code>. 车场名称
     */
    public String getParkName();

    /**
     * Setter for <code>test.cw_sum.time</code>.
     */
    public ICwSum setTime(LocalDateTime value);

    /**
     * Getter for <code>test.cw_sum.time</code>.
     */
    public LocalDateTime getTime();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface ICwSum
     */
    public void from(ICwSum from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface ICwSum
     */
    public <E extends ICwSum> E into(E into);

        @Override
        public default ICwSum fromJson(io.vertx.core.json.JsonObject json) {
            CwSum clazz = (CwSum) json.mapTo(CwSum.class);
            this.from(clazz);
            return this;
        }


        @Override
        public default io.vertx.core.json.JsonObject toJson() {
            io.vertx.core.json.JsonObject json = io.vertx.core.json.JsonObject.mapFrom(this);
            return json;
        }

}
